### ISSUE TITLE
Error while running the svelte/store example

### ISSUE THREAD

**Issue by jrabary** [manzt/anywidget#207]
I'm giving a try to this very new feature https://github.com/manzt/anywidget/tree/main/packages/svelte but my example fails with `count` having `NAN` value.
The svelte code is exactly the same as in the readme. The python code is like below

```
class SvelteCounter(anywidget.AnyWidget):
    _esm = "http://localhost:5173/dist/index.js?anywidget"
    count = traitlets.Int().tag(sync=True)
    
counter = SvelteCounter()
counter
```

**Comment by manzt** [comment]
Thanks for your interest! The `@anywidget/svelte` library is still very experimental. With that said, an NaN makes me think that count in the frontend is somehow undefined at some point.

It seems you might be using the anywidget vite plugin. I haven't tested the svelte package with this, but I'm guessing there is some issue with the plugin's HMR and the global store.

My recommendation at the moment is to use Rollup + anywidget's builtin HMR, rather than Vite.

```js
// rollup.config.js
import svelte from "rollup-plugin-svelte";
import resolve from "@rollup/plugin-node-resolve";

export default {
  input: "index.js",
  output: { file: "static/bundle.js", format: "esm" },
  plugins: [
    svelte({ emitCss: false }),
    resolve(),
  ]
}
```

```sh
rollup -c rollup.config.js --watch
```

```python
class SvelteCounter(anywidget.AnyWidget):
    _esm = "static/bundle.js"
    count = traitlets.Int(0).tag(sync=True)
    
counter = SvelteCounter()
counter
```

**Comment by jrabary** [comment]
Indeed, I'm using vite to build the project. You adapter is really cool. I have been looking for a long time a way to easily create Jupiter widget for our tools https://github.com/pixano/pixano that uses svelte under the hood. I am definitely going to try it for this project.

**Comment by jrabary** [comment]
How do you retrieve a complex type (like python dict or js object) from the store ?

**Comment by manzt** [comment]
> I have been looking for a long time a way to easily create Jupiter widget for our tools [pixano/pixano](https://github.com/pixano/pixano) that uses svelte under the hood.

That's great to hear! Hope I can help further support this work.

> How do you retrieve a complex type (like python dict or js object) from the store ?

ipywidgets takes care of serializing objects. From [the docs](https://ipywidgets.readthedocs.io/en/7.x/examples/Widget%20Low%20Level.html#Serialization-of-widget-attributes):

> Widget trait attributes tagged with `sync=True` are synchronized with the JavaScript model instance on the JavaScript side. For this reason, they need to be serialized into json.
>
> By default, basic Python types such as `int`, `float`, `list` and `dict` are simply be mapped to `Number`, `Array` and `Object`. For more complex types, serializers and de-serializers must be specified on both the Python side and the JavaScript side.

The auto serialization works recursively as well (think `json.dumps(obj)`), so you only really need to implement custom serializers if you have have defined more complex types (e.g., a class) that you want to send to the front-end.

```python
class Widget(anywidget.AnyWidget):
    _esm = "index.js"
    person = traitlets.Any().tag(sync=True)

Widget(person= { "age": 56, "name": { "first": "Elmer", "last": "Fudd"  } })
```

will create an object on the javascript side:

```javascript
let { person } = stores;
person.age // 56
person.name // { first: "Elmer", last: "Fudd" }
```

ipywidgets also takes care of `bytes`, which are serialized to JavaScript `DataView` in your store.

**Comment by jrabary** [comment]
Thank you very much for these examples. I'll keep you informed on the use of anywidget in our project.

**Comment by manzt** [comment]
I just released v0.0.2, which should be compatible with the `@anywidget/vite` plugin.

```sh
npm i --save-dev vite @sveltejs/vite-plugin-svelte @anywidget/vite
npm i svelte @anywidget/svelte
```

```js
// vite.config.js
import { defineConfig } from "vite";
import { svelte } from "@sveltejs/vite-plugin-svelte";
import anywidget from "@anywidget/vite";

export default defineConfig({
	plugins: [anywidget(), svelte({ hot: false })],
});
```

```js
// index.js
import { createRender } from "@anywidget/svelte";
import Counter from "./Counter.svelte";

export const render = createRender(Counter);
```

```svelte
<script>
	import { stores } from "@anywidget/svelte";
	let { count } = stores;
</script>

<button on:click={() => $count++}>
	Count is: {$count}
</button>

<style>
	button {
		background: lightgreen;
		border: 1px solid #ccc;
		border-radius: 4px;
		padding: 0.5em 1em;
	}
</style>
```

```python
import anywidget
import traitlets

class Counter(anywidget.AnyWidget):
    _esm = "http://localhost:5173/index.js?anywidget"
    count = traitlets.Int(0).tag(sync=True)

Counter()
```

**Comment by pnsvk** [comment]
@manzt thank you for your inputs, but I am still not able to get it to work.. sure I am missing out something.. I am getting started with svelte and seeing it would be great value to glue between other libraries that I would want to leverage, like d3.js, cytoscape etc. for my widgets.. 

can you please make a video on your utube channel ? -- couldn't find one on: [@trevormanz3741](https://www.youtube.com/@trevormanz3741/videos)

fyi.. following is the error dump, when tried to `vite build`

(my-venv-3.10) DST-C02G42G1MD6T:hello dt236742$ npm run build

> build
> vite build

vite v4.4.8 building for production...
✓ 0 modules transformed.
✓ built in 10ms
Could not resolve entry module "index.html".
error during build:
RollupError: Could not resolve entry module "index.html".
    at error (file:///Users/dt236742/my-notebooks/sql-play/my-widgets/hello/node_modules/rollup/dist/es/shared/node-entry.js:2245:30)
    at ModuleLoader.loadEntryModule (file:///Users/dt236742/my-notebooks/sql-play/my-widgets/hello/node_modules/rollup/dist/es/shared/node-entry.js:24695:20)
    at async Promise.all (index 0)

**Comment by manzt** [comment]
The issue you are running into is related to configuring `vite`, not the anywidget plugin or adapter. I recommend familiarizing yourself with Vite's documentation if you plan to use this tool as there are many learning resources online.

With that said, the problem arises from not specifying `build.lib` in your vite.config.js. Vite normally assumes there to be an `index.html` that serves as the "root" of your app, but in the case of building a JS library (your widget ESM) you need to tell Vite where to start. This is covered in the [bundling section](https://anywidget.dev/en/bundling/#vite) in our documentation.

```js
// vite.config.js
import { defineConfig } from "vite";
import { svelte } from "@sveltejs/vite-plugin-svelte";
import anywidget from "@anywidget/vite";

export default defineConfig({
  build: {
    outDir: "static",
    lib: {
      entry: "index.js",
      formats: ["es"],
      fileName: "bundle",
    }
  },
  plugins: [anywidget(), svelte({ hot: false })],
});
```

> can you please make a video on your utube channel ?

I'm hoping to find some time to record some videos, but I don't anticipate being able to for a little while.

**Comment by pnsvk** [comment]
Thank you so much.. @manzt 
I will try to make a video and post it here some time this/next week..

![ED2D27D0-9B10-4292-B7BF-5EDB5614429F](https://github.com/manzt/anywidget/assets/30823233/f5209975-e5a8-4019-a99c-129481a5ed62)
